export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/sign-in'
export const REGISTRATION_ROUTE = '/sign-up'
export const PRODUCTS_ROUTE = '/'
export const DEVICE_ROUTE = '/device'
export const CART_ROUTE = '/cart'
export const ABOUT_US_ROUTE = '/about_us'
export const PAYMENT_ROUTE = '/payment'
